import type { Metadata } from "next";
import { Geist, Geist_Mono, Playwrite_IN } from "next/font/google";
import "./globals.css";

const playwriteIN = Playwrite_IN({
  variable: "--font-playwrite-in",
  weight: ['400'],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playwriteIN.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
